### ISSUE TITLE
Better cooperation with PKL_eD?

### ISSUE THREAD

**Issue by DreymaR** [Portable-Keyboard-Layout/Portable-Keyboard-Layout#13]
Hi! As you may know, I have my own variant of PKL, namely [PKL_eD](https://github.com/DreymaR/BigBagKbdTrixPKL) going. Based originally on a decompiled PKL v0.4, it has many of my preferred changes as well as my Colemak/Tarmak layouts.

I've linked to this repo in the README, but is there more we should do to point to each other and exchange stuff? I guess it's too late to make my repo a fork of this one since I didn't know of this repo when I made mine. 🤔

**Comment by rubo77** [comment]
Sure, we could link to each other in the Readme and in the top message on GitHub.

I will checkout your repo later and see about the similarities....

**Comment by DreymaR** [comment]
I've linked to this repo in my latest version. Nice! ^_^

**Comment by rubo77** [comment]
In your repo you have a button "edit"at the top. For the slogan and URL

**Comment by DreymaR** [comment]
Oh, I see. But this repo has no slogan or website now?
