### ISSUE TITLE
Releases Should Include Zip Files

### ISSUE THREAD

**Issue by joel0** [Portable-Keyboard-Layout/Portable-Keyboard-Layout#2]
I think the releases should include zip files of the portable layouts and a master release with the program and layouts (excluding source).  See https://github.com/joel0/Portable-Keyboard-Layout/releases for an example of what I mean.

**Comment by rubo77** [comment]
How did you create the release with extra files?

**Comment by joel0** [comment]
When you edit the release, you can attach binary files.  I created the zip files from my local copy of the repository.

**Comment by rubo77** [comment]
you want to take control of the PKL on github? I just copied it here, cause farkas said, he has no time for this any more?

Then I would just delete my fork and yours will be the main fork

**Comment by rubo77** [comment]
i went back to QWERTZ cause still after 6 years of only using my new layout, I was still faster on QWERTZ, which i used 10 years already before. It seems like if you are old and once you are really fast in one layout, learning another is not possible any more :`-(

**Comment by joel0** [comment]
I think you can make an org and add me to it (maybe, I haven't done it).  My free time fluctuates often and I don't think I'd make a good sole maintainer.

For me, speed is a low priority as long as I am fluent with the layout.  I regularly switch between Workman and QWERTY.  When I have to type on QWERTY, I can feel a lot more movement for the same amount of words.  That is why I find Workman more desirable to use than QWERTY.  But a layout is simply a personal preference, which has no "correct" answer.

**Comment by rubo77** [comment]
You are now co-owner here

**Comment by joel0** [comment]
Thanks, I appreciate it.  I've added the zip files for the release.
